<?php

namespace Database\Seeders;

use App\Models\Municipality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $municipalities=[
            ['name'=>'MEDELLIN'                      ,'code'=>'1'  ],
            ['name'=>'ABEJORRAL'                     ,'code'=>'4'  ],
            ['name'=>'ABRIAQUI'                      ,'code'=>'7'  ],
            ['name'=>'ALEJANDRIA'                    ,'code'=>'10' ],
            ['name'=>'AMAGA'                         ,'code'=>'13' ],
            ['name'=>'AMALFI'                        ,'code'=>'16' ],
            ['name'=>'ANDES'                         ,'code'=>'19' ],
            ['name'=>'ANGELOPOLIS'                   ,'code'=>'22' ],
            ['name'=>'ANGOSTURA'                     ,'code'=>'25' ],
            ['name'=>'ANORI'                         ,'code'=>'28' ],
            ['name'=>'ANTIOQUIA'                     ,'code'=>'31' ],
            ['name'=>'ANZA'                          ,'code'=>'34' ],
            ['name'=>'APARTADO'                      ,'code'=>'35' ],
            ['name'=>'ARBOLETES'                     ,'code'=>'37' ],
            ['name'=>'ARGELIA'                       ,'code'=>'39' ],
            ['name'=>'ARMENIA'                       ,'code'=>'40' ],
            ['name'=>'BARBOSA'                       ,'code'=>'43' ],
            ['name'=>'BELMIRA'                       ,'code'=>'46' ],
            ['name'=>'BELLO'                         ,'code'=>'49' ],
            ['name'=>'BETANIA'                       ,'code'=>'52' ],
            ['name'=>'BETULIA'                       ,'code'=>'55' ],
            ['name'=>'BOLIVAR'                       ,'code'=>'58' ],
            ['name'=>'BURITICA'                      ,'code'=>'61' ],
            ['name'=>'BRICEÑO'                       ,'code'=>'62' ],
            ['name'=>'CACERES'                       ,'code'=>'64' ],
            ['name'=>'CAICEDO'                       ,'code'=>'67' ],
            ['name'=>'CALDAS'                        ,'code'=>'70' ],
            ['name'=>'CAMPAMENTO'                    ,'code'=>'73' ],
            ['name'=>'CAÑASGORDAS'                   ,'code'=>'76' ],
            ['name'=>'CARACOLI'                      ,'code'=>'78' ],
            ['name'=>'CARAMANTA'                     ,'code'=>'79' ],
            ['name'=>'CAREPA'                        ,'code'=>'80' ],
            ['name'=>'CARMEN DE VIBORAL'             ,'code'=>'82' ],
            ['name'=>'CAROLINA'                      ,'code'=>'85' ],
            ['name'=>'CAUCASIA'                      ,'code'=>'88' ],
            ['name'=>'CISNEROS'                      ,'code'=>'91' ],
            ['name'=>'COCORNA'                       ,'code'=>'94' ],
            ['name'=>'CONCEPCION'                    ,'code'=>'97' ],
            ['name'=>'CONCORDIA'                     ,'code'=>'100'],
            ['name'=>'COPACABANA'                    ,'code'=>'103'],
            ['name'=>'CHIGORODO'                     ,'code'=>'106'],
            ['name'=>'DABEIBA'                       ,'code'=>'109'],
            ['name'=>'DON MATIAS'                    ,'code'=>'112'],
            ['name'=>'EBEJICO'                       ,'code'=>'115'],
            ['name'=>'EL BAGRE'                      ,'code'=>'117'],
            ['name'=>'ENTRERRIOS'                    ,'code'=>'118'],
            ['name'=>'ENVIGADO'                      ,'code'=>'121'],
            ['name'=>'FREDONIA'                      ,'code'=>'124'],
            ['name'=>'FRONTINO'                      ,'code'=>'127'],
            ['name'=>'GIRALDO'                       ,'code'=>'130'],
            ['name'=>'GIRARDOTA'                     ,'code'=>'133'],
            ['name'=>'GOMEZ PLATA'                   ,'code'=>'136'],
            ['name'=>'GRANADA'                       ,'code'=>'139'],
            ['name'=>'GUADALUPE'                     ,'code'=>'140'],
            ['name'=>'GUARNE'                        ,'code'=>'142'],
            ['name'=>'GUATAPE'                       ,'code'=>'145'],
            ['name'=>'HELICONIA'                     ,'code'=>'148'],
            ['name'=>'HISPANIA'                      ,'code'=>'150'],
            ['name'=>'ITAGUI'                        ,'code'=>'151'],
            ['name'=>'ITUANGO'                       ,'code'=>'154'],
            ['name'=>'JARDIN'                        ,'code'=>'157'],
            ['name'=>'JERICO'                        ,'code'=>'160'],
            ['name'=>'LA CEJA'                       ,'code'=>'163'],
            ['name'=>'LA ESTRELLA'                   ,'code'=>'166'],
            ['name'=>'PUERTO NARE-LA MAGDALENA'      ,'code'=>'168'],
            ['name'=>'LA UNION'                      ,'code'=>'169'],
            ['name'=>'LA PINTADA'                    ,'code'=>'170'],
            ['name'=>'LIBORINA'                      ,'code'=>'172'],
            ['name'=>'MACEO'                         ,'code'=>'175'],
            ['name'=>'MARINILLA'                     ,'code'=>'178'],
            ['name'=>'MONTEBELLO'                    ,'code'=>'181'],
            ['name'=>'MURINDO'                       ,'code'=>'184'],
            ['name'=>'MUTATA'                        ,'code'=>'187'],
            ['name'=>'NARIÑO'                        ,'code'=>'190'],
            ['name'=>'NECHI'                         ,'code'=>'191'],
            ['name'=>'NECOCLI'                       ,'code'=>'192'],
            ['name'=>'OLAYA'                         ,'code'=>'193'],
            ['name'=>'PEÑOL'                         ,'code'=>'196'],
            ['name'=>'PEQUE'                         ,'code'=>'199'],
            ['name'=>'PUEBLORRICO'                   ,'code'=>'202'],
            ['name'=>'PUERTO BERRIO'                 ,'code'=>'205'],
            ['name'=>'PUERTO TRIUNFO'                ,'code'=>'206'],
            ['name'=>'REMEDIOS'                      ,'code'=>'208'],
            ['name'=>'RETIRO'                        ,'code'=>'211'],
            ['name'=>'RIONEGRO'                      ,'code'=>'214'],
            ['name'=>'SABANALARGA'                   ,'code'=>'217'],
            ['name'=>'SABANETA'                      ,'code'=>'218'],
            ['name'=>'SALGAR'                        ,'code'=>'220'],
            ['name'=>'SAN ANDRES'                    ,'code'=>'223'],
            ['name'=>'SAN CARLOS'                    ,'code'=>'226'],
            ['name'=>'SAN FRANCISCO'                 ,'code'=>'227'],
            ['name'=>'SAN JERONIMO'                  ,'code'=>'229'],
            ['name'=>'SAN JOSE DE LA MONTAÑA'        ,'code'=>'230'],
            ['name'=>'SAN JUAN DE URABA'             ,'code'=>'231'],
            ['name'=>'SAN LUIS'                      ,'code'=>'232'],
            ['name'=>'SAN PEDRO'                     ,'code'=>'235'],
            ['name'=>'SAN PEDRO DE URABA'            ,'code'=>'237'],
            ['name'=>'SAN RAFAEL'                    ,'code'=>'238'],
            ['name'=>'SAN ROQUE'                     ,'code'=>'241'],
            ['name'=>'SAN VICENTE'                   ,'code'=>'244'],
            ['name'=>'SANTA BARBARA'                 ,'code'=>'247'],
            ['name'=>'SANTA ROSA DE OSOS'            ,'code'=>'250'],
            ['name'=>'SANTO DOMINGO'                 ,'code'=>'253'],
            ['name'=>'SANTUARIO'                     ,'code'=>'256'],
            ['name'=>'SEGOVIA'                       ,'code'=>'259'],
            ['name'=>'SONSON'                        ,'code'=>'262'],
            ['name'=>'SOPETRAN'                      ,'code'=>'265'],
            ['name'=>'TAMESIS'                       ,'code'=>'268'],
            ['name'=>'TARAZA'                        ,'code'=>'270'],
            ['name'=>'TARSO'                         ,'code'=>'271'],
            ['name'=>'TITIRIBI'                      ,'code'=>'274'],
            ['name'=>'TOLEDO'                        ,'code'=>'277'],
            ['name'=>'TURBO'                         ,'code'=>'280'],
            ['name'=>'URAMITA'                       ,'code'=>'282'],
            ['name'=>'URRAO'                         ,'code'=>'283'],
            ['name'=>'VALDIVIA'                      ,'code'=>'286'],
            ['name'=>'VALPARAISO'                    ,'code'=>'289'],
            ['name'=>'VEGACHI'                       ,'code'=>'290'],
            ['name'=>'VIGIA DEL FUERTE'              ,'code'=>'291'],
            ['name'=>'VENECIA'                       ,'code'=>'292'],
            ['name'=>'YALI'                          ,'code'=>'293'],
            ['name'=>'YARUMAL'                       ,'code'=>'295'],
            ['name'=>'YOLOMBO'                       ,'code'=>'298'],
            ['name'=>'YONDO-CASABE'                  ,'code'=>'300'],
            ['name'=>'ZARAGOZA'                      ,'code'=>'301'],
            ['name'=>'BARRANQUILLA'                  ,'code'=>'1'  ],
            ['name'=>'BARANOA'                       ,'code'=>'4'  ],
            ['name'=>'CAMPO DE LA CRUZ'              ,'code'=>'7'  ],
            ['name'=>'CANDELARIA'                    ,'code'=>'10' ],
            ['name'=>'GALAPA'                        ,'code'=>'13' ],
            ['name'=>'JUAN DE ACOSTA'                ,'code'=>'16' ],
            ['name'=>'LURUACO'                       ,'code'=>'19' ],
            ['name'=>'MALAMBO'                       ,'code'=>'22' ],
            ['name'=>'MANATI'                        ,'code'=>'25' ],
            ['name'=>'PALMAR DE VARELA'              ,'code'=>'28' ],
            ['name'=>'PIOJO'                         ,'code'=>'31' ],
            ['name'=>'POLONUEVO'                     ,'code'=>'34' ],
            ['name'=>'PONEDERA'                      ,'code'=>'35' ],
            ['name'=>'PUERTO COLOMBIA'               ,'code'=>'37' ],
            ['name'=>'REPELON'                       ,'code'=>'40' ],
            ['name'=>'SABANAGRANDE'                  ,'code'=>'43' ],
            ['name'=>'SABANALARGA'                   ,'code'=>'46' ],
            ['name'=>'SANTA LUCIA'                   ,'code'=>'47' ],
            ['name'=>'SANTO TOMAS'                   ,'code'=>'49' ],
            ['name'=>'SOLEDAD'                       ,'code'=>'52' ],
            ['name'=>'SUAN'                          ,'code'=>'55' ],
            ['name'=>'TUBARA'                        ,'code'=>'58' ],
            ['name'=>'USIACURI'                      ,'code'=>'61' ],
            ['name'=>'CARTAGENA'                     ,'code'=>'1'  ],
            ['name'=>'ACHI'                          ,'code'=>'4'  ],
            ['name'=>'ARENAL'                        ,'code'=>'5'  ],
            ['name'=>'ALTOS DEL ROSARIO'             ,'code'=>'6'  ],
            ['name'=>'ARJONA'                        ,'code'=>'7'  ],
            ['name'=>'ARROYO HONDO'                  ,'code'=>'9'  ],
            ['name'=>'BARRANCO DE LOBA'              ,'code'=>'10' ],
            ['name'=>'CALAMAR'                       ,'code'=>'13' ],
            ['name'=>'CANTAGALLO'                    ,'code'=>'14' ],
            ['name'=>'CICUCO'                        ,'code'=>'15' ],
            ['name'=>'CORDOBA'                       ,'code'=>'16' ],
            ['name'=>'CLEMENCIA'                     ,'code'=>'18' ],
            ['name'=>'EL CARMEN DE BOLIVAR'          ,'code'=>'22' ],
            ['name'=>'EL GUAMO'                      ,'code'=>'25' ],
            ['name'=>'HATILLO DE LOBA'               ,'code'=>'26' ],
            ['name'=>'EL PEÑON'                      ,'code'=>'27' ],
            ['name'=>'MAGANGUE'                      ,'code'=>'28' ],
            ['name'=>'MAHATES'                       ,'code'=>'31' ],
            ['name'=>'MARGARITA'                     ,'code'=>'37' ],
            ['name'=>'MARIA LA BAJA'                 ,'code'=>'40' ],
            ['name'=>'MONTECRISTO'                   ,'code'=>'41' ],
            ['name'=>'MOMPOS'                        ,'code'=>'43' ],
            ['name'=>'MORALES'                       ,'code'=>'44' ],
            ['name'=>'NOROSI'                        ,'code'=>'50' ],
            ['name'=>'PINILLOS'                      ,'code'=>'59' ],
            ['name'=>'REGIDOR'                       ,'code'=>'63' ],
            ['name'=>'RIOVIEJO'                      ,'code'=>'65' ],
            ['name'=>'SAN ESTANISLAO'                ,'code'=>'70' ],
            ['name'=>'SAN CRISTOBAL'                 ,'code'=>'72' ],
            ['name'=>'SAN FERNANDO'                  ,'code'=>'73' ],
            ['name'=>'SAN JACINTO'                   ,'code'=>'76' ],
            ['name'=>'SAN JACINTO DEL CAUCA'         ,'code'=>'78' ],
            ['name'=>'SAN JUAN NEPOMUCENO'           ,'code'=>'79' ],
            ['name'=>'SAN MARTIN DE LOBA'            ,'code'=>'82' ],
            ['name'=>'SAN PABLO'                     ,'code'=>'84' ],
            ['name'=>'SANTA CATALINA'                ,'code'=>'91' ],
            ['name'=>'SANTA ROSA'                    ,'code'=>'94' ],
            ['name'=>'SANTA ROSA DEL SUR'            ,'code'=>'95' ],
            ['name'=>'SIMITI'                        ,'code'=>'97' ],
            ['name'=>'SOPLAVIENTO'                   ,'code'=>'106'],
            ['name'=>'TALAIGUA NUEVO'                ,'code'=>'110'],
            ['name'=>'TIQUISIO (PTO. RICO)'          ,'code'=>'113'],
            ['name'=>'TURBACO'                       ,'code'=>'118'],
            ['name'=>'TURBANA'                       ,'code'=>'121'],
            ['name'=>'VILLANUEVA'                    ,'code'=>'124'],
            ['name'=>'ZAMBRANO'                      ,'code'=>'127'],
            ['name'=>'TUNJA'                         ,'code'=>'1'  ],
            ['name'=>'ALMEIDA'                       ,'code'=>'7'  ],
            ['name'=>'AQUITANIA (PUEBLOVIEJO)'       ,'code'=>'8'  ],
            ['name'=>'ARCABUCO'                      ,'code'=>'10' ],
            ['name'=>'BELEN'                         ,'code'=>'13' ],
            ['name'=>'BERBEO'                        ,'code'=>'16' ],
            ['name'=>'BETEITIVA'                     ,'code'=>'19' ],
            ['name'=>'BOAVITA'                       ,'code'=>'22' ],
            ['name'=>'BOYACA'                        ,'code'=>'25' ],
            ['name'=>'BRICEÑO'                       ,'code'=>'28' ],
            ['name'=>'BUENAVISTA'                    ,'code'=>'31' ],
            ['name'=>'BUSBANZA'                      ,'code'=>'34' ],
            ['name'=>'CALDAS'                        ,'code'=>'37' ],
            ['name'=>'CAMPOHERMOSO'                  ,'code'=>'40' ],
            ['name'=>'CERINZA'                       ,'code'=>'43' ],
            ['name'=>'CIENEGA'                       ,'code'=>'46' ],
            ['name'=>'COMBITA'                       ,'code'=>'49' ],
            ['name'=>'COPER'                         ,'code'=>'52' ],
            ['name'=>'CORRALES'                      ,'code'=>'55' ],
            ['name'=>'COVARACHIA'                    ,'code'=>'58' ],
            ['name'=>'CUBARA'                        ,'code'=>'59' ],
            ['name'=>'CUCAITA'                       ,'code'=>'60' ],
            ['name'=>'CUITIVA'                       ,'code'=>'61' ],
            ['name'=>'CHINAVITA'                     ,'code'=>'64' ],
            ['name'=>'CHIQUINQUIRA'                  ,'code'=>'67' ],
            ['name'=>'CHIQUIZA'                      ,'code'=>'68' ],
            ['name'=>'CHISCAS'                       ,'code'=>'70' ],
            ['name'=>'CHITA'                         ,'code'=>'73' ],
            ['name'=>'CHITARAQUE'                    ,'code'=>'76' ],
            ['name'=>'CHIVATA'                       ,'code'=>'77' ],
            ['name'=>'CHIVOR'                        ,'code'=>'78' ],
            ['name'=>'DUITAMA'                       ,'code'=>'79' ],
            ['name'=>'EL COCUY'                      ,'code'=>'82' ],
            ['name'=>'EL ESPINO'                     ,'code'=>'85' ],
            ['name'=>'FIRAVITOBA'                    ,'code'=>'88' ],
            ['name'=>'FLORESTA'                      ,'code'=>'91' ],
            ['name'=>'GACHANTIVA'                    ,'code'=>'94' ],
            ['name'=>'GAMEZA'                        ,'code'=>'97' ],
            ['name'=>'GARAGOA'                       ,'code'=>'100'],
            ['name'=>'GUACAMAYAS'                    ,'code'=>'103'],
            ['name'=>'GUATEQUE'                      ,'code'=>'106'],
            ['name'=>'GUAYATA'                       ,'code'=>'109'],
            ['name'=>'GUICAN'                        ,'code'=>'112'],
            ['name'=>'IZA'                           ,'code'=>'118'],
            ['name'=>'JENESANO'                      ,'code'=>'121'],
            ['name'=>'JERICO'                        ,'code'=>'124'],
            ['name'=>'LABRANZAGRANDE'                ,'code'=>'127'],
            ['name'=>'LA CAPILLA'                    ,'code'=>'130'],
            ['name'=>'LA UVITA'                      ,'code'=>'136'],
            ['name'=>'LA VICTORIA'                   ,'code'=>'137'],
            ['name'=>'VILLA DE LEIVA'                ,'code'=>'139'],
            ['name'=>'MACANAL'                       ,'code'=>'142'],
            ['name'=>'MARIPI'                        ,'code'=>'148'],
            ['name'=>'MIRAFLORES'                    ,'code'=>'151'],
            ['name'=>'MONGUA'                        ,'code'=>'154'],
            ['name'=>'MONGUI'                        ,'code'=>'157'],
            ['name'=>'MONIQUIRA'                     ,'code'=>'160'],
            ['name'=>'MOTAVITA'                      ,'code'=>'161'],
            ['name'=>'MUZO'                          ,'code'=>'163'],
            ['name'=>'NOBSA'                         ,'code'=>'166'],
            ['name'=>'NUEVO COLON'                   ,'code'=>'169'],
            ['name'=>'OICATA'                        ,'code'=>'173'],
            ['name'=>'OTANCHE'                       ,'code'=>'176'],
            ['name'=>'PACHAVITA'                     ,'code'=>'178'],
            ['name'=>'PAEZ'                          ,'code'=>'179'],
            ['name'=>'PAIPA'                         ,'code'=>'181'],
            ['name'=>'PAJARITO'                      ,'code'=>'184'],
            ['name'=>'PANQUEBA'                      ,'code'=>'187'],
            ['name'=>'PAUNA'                         ,'code'=>'190'],
            ['name'=>'PAYA'                          ,'code'=>'193'],
            ['name'=>'PAZ DE RIO'                    ,'code'=>'199'],
            ['name'=>'PESCA'                         ,'code'=>'202'],
            ['name'=>'PISBA'                         ,'code'=>'205'],
            ['name'=>'PUERTO BOYACA'                 ,'code'=>'214'],
            ['name'=>'QUIPAMA'                       ,'code'=>'215'],
            ['name'=>'RAMIRIQUI'                     ,'code'=>'217'],
            ['name'=>'RAQUIRA'                       ,'code'=>'220'],
            ['name'=>'RONDON'                        ,'code'=>'223'],
            ['name'=>'SABOYA'                        ,'code'=>'226'],
            ['name'=>'SACHICA'                       ,'code'=>'232'],
            ['name'=>'SAMACA'                        ,'code'=>'235'],
            ['name'=>'SAN EDUARDO'                   ,'code'=>'237'],
            ['name'=>'SAN JOSE DE PARE'              ,'code'=>'238'],
            ['name'=>'SAN LUIS DE GACENO'            ,'code'=>'241'],
            ['name'=>'SAN MATEO'                     ,'code'=>'247'],
            ['name'=>'SAN MIGUEL DE SEMA'            ,'code'=>'248'],
            ['name'=>'SAN PABLO DE BORBUR'           ,'code'=>'249'],
            ['name'=>'SANTANA'                       ,'code'=>'250'],
            ['name'=>'SANTA MARIA'                   ,'code'=>'251'],
            ['name'=>'SANTA ROSA DE VITERBO'         ,'code'=>'253'],
            ['name'=>'SANTA SOFIA'                   ,'code'=>'256'],
            ['name'=>'SATIVANORTE'                   ,'code'=>'259'],
            ['name'=>'SATIVASUR'                     ,'code'=>'262'],
            ['name'=>'SIACHOQUE'                     ,'code'=>'265'],
            ['name'=>'SOATA'                         ,'code'=>'268'],
            ['name'=>'SOCOTA'                        ,'code'=>'271'],
            ['name'=>'SOCHA'                         ,'code'=>'274'],
            ['name'=>'SOGAMOSO'                      ,'code'=>'277'],
            ['name'=>'SOMONDOCO'                     ,'code'=>'280'],
            ['name'=>'SORA'                          ,'code'=>'281'],
            ['name'=>'SORACA'                        ,'code'=>'282'],
            ['name'=>'SOTAQUIRA'                     ,'code'=>'283'],
            ['name'=>'SUSACON'                       ,'code'=>'286'],
            ['name'=>'SUTAMARCHAN'                   ,'code'=>'289'],
            ['name'=>'SUTATENZA'                     ,'code'=>'292'],
            ['name'=>'TASCO'                         ,'code'=>'298'],
            ['name'=>'TENZA'                         ,'code'=>'301'],
            ['name'=>'TIBANA'                        ,'code'=>'304'],
            ['name'=>'TIBASOSA'                      ,'code'=>'307'],
            ['name'=>'TINJACA'                       ,'code'=>'310'],
            ['name'=>'TIPACOQUE'                     ,'code'=>'311'],
            ['name'=>'TOCA'                          ,'code'=>'313'],
            ['name'=>'TOGUI'                         ,'code'=>'316'],
            ['name'=>'TOPAGA'                        ,'code'=>'319'],
            ['name'=>'TOTA'                          ,'code'=>'322'],
            ['name'=>'TUNUNGUA'                      ,'code'=>'324'],
            ['name'=>'TURMEQUE'                      ,'code'=>'325'],
            ['name'=>'TUTA'                          ,'code'=>'328'],
            ['name'=>'TUTAZA'                        ,'code'=>'331'],
            ['name'=>'UMBITA'                        ,'code'=>'334'],
            ['name'=>'VENTAQUEMADA'                  ,'code'=>'337'],
            ['name'=>'VIRACACHA'                     ,'code'=>'340'],
            ['name'=>'ZETAQUIRA'                     ,'code'=>'346'],
            ['name'=>'MANIZALES'                     ,'code'=>'1'  ],
            ['name'=>'AGUADAS'                       ,'code'=>'4'  ],
            ['name'=>'ANSERMA'                       ,'code'=>'7'  ],
            ['name'=>'ARANZAZU'                      ,'code'=>'13' ],
            ['name'=>'BELALCAZAR'                    ,'code'=>'22' ],
            ['name'=>'CHINCHINA'                     ,'code'=>'34' ],
            ['name'=>'FILADELFIA'                    ,'code'=>'37' ],
            ['name'=>'LA DORADA'                     ,'code'=>'49' ],
            ['name'=>'LA MERCED'                     ,'code'=>'52' ],
            ['name'=>'MANZANARES'                    ,'code'=>'55' ],
            ['name'=>'MARMATO'                       ,'code'=>'58' ],
            ['name'=>'MARQUETALIA'                   ,'code'=>'61' ],
            ['name'=>'MARULANDA'                     ,'code'=>'67' ],
            ['name'=>'NEIRA'                         ,'code'=>'76' ],
            ['name'=>'NORCASIA'                      ,'code'=>'78' ],
            ['name'=>'PACORA'                        ,'code'=>'79' ],
            ['name'=>'PALESTINA'                     ,'code'=>'82' ],
            ['name'=>'PENSILVANIA'                   ,'code'=>'85' ],
            ['name'=>'RIOSUCIO'                      ,'code'=>'103'],
            ['name'=>'RISARALDA'                     ,'code'=>'106'],
            ['name'=>'SALAMINA'                      ,'code'=>'109'],
            ['name'=>'SAMANA'                        ,'code'=>'115'],
            ['name'=>'SAN JOSE'                      ,'code'=>'120'],
            ['name'=>'SUPIA'                         ,'code'=>'124'],
            ['name'=>'VICTORIA'                      ,'code'=>'127'],
            ['name'=>'VILLAMARIA'                    ,'code'=>'130'],
            ['name'=>'VITERBO'                       ,'code'=>'133'],
            ['name'=>'POPAYAN'                       ,'code'=>'1'  ],
            ['name'=>'ALMAGUER'                      ,'code'=>'4'  ],
            ['name'=>'ARGELIA'                       ,'code'=>'5'  ],
            ['name'=>'BALBOA'                        ,'code'=>'6'  ],
            ['name'=>'BOLIVAR'                       ,'code'=>'7'  ],
            ['name'=>'BUENOS AIRES'                  ,'code'=>'10' ],
            ['name'=>'CAJIBIO'                       ,'code'=>'13' ],
            ['name'=>'CALDONO'                       ,'code'=>'16' ],
            ['name'=>'CALOTO'                        ,'code'=>'19' ],
            ['name'=>'CORINTO'                       ,'code'=>'22' ],
            ['name'=>'EL TAMBO'                      ,'code'=>'25' ],
            ['name'=>'FLORENCIA'                     ,'code'=>'27' ],
            ['name'=>'GUAPI'                         ,'code'=>'28' ],
            ['name'=>'GUACHENE'                      ,'code'=>'29' ],
            ['name'=>'INZA'                          ,'code'=>'31' ],
            ['name'=>'JAMBALO'                       ,'code'=>'34' ],
            ['name'=>'LA SIERRA'                     ,'code'=>'37' ],
            ['name'=>'LA VEGA'                       ,'code'=>'40' ],
            ['name'=>'LOPEZ (MICAY)'                 ,'code'=>'43' ],
            ['name'=>'MERCADERES'                    ,'code'=>'46' ],
            ['name'=>'MIRANDA'                       ,'code'=>'49' ],
            ['name'=>'MORALES'                       ,'code'=>'52' ],
            ['name'=>'PADILLA'                       ,'code'=>'53' ],
            ['name'=>'PAEZ (BELALCAZAR)'             ,'code'=>'55' ],
            ['name'=>'PATIA (EL BORDO)'              ,'code'=>'58' ],
            ['name'=>'PIAMONTE'                      ,'code'=>'60' ],
            ['name'=>'PIENDAMO'                      ,'code'=>'61' ],
            ['name'=>'PUERTO TEJADA'                 ,'code'=>'64' ],
            ['name'=>'PURACE (COCONUCO)'             ,'code'=>'67' ],
            ['name'=>'ROSAS'                         ,'code'=>'70' ],
            ['name'=>'SAN SEBASTIAN'                 ,'code'=>'73' ],
            ['name'=>'SANTANDER DE QUILICHAO'        ,'code'=>'76' ],
            ['name'=>'SANTA ROSA'                    ,'code'=>'79' ],
            ['name'=>'SILVIA'                        ,'code'=>'82' ],
            ['name'=>'SOTARA (PAISPAMBA)'            ,'code'=>'85' ],
            ['name'=>'SUCRE'                         ,'code'=>'86' ],
            ['name'=>'SUAREZ'                        ,'code'=>'87' ],
            ['name'=>'TIMBIO'                        ,'code'=>'88' ],
            ['name'=>'TIMBIQUI'                      ,'code'=>'91' ],
            ['name'=>'TORIBIO'                       ,'code'=>'94' ],
            ['name'=>'TOTORO'                        ,'code'=>'97' ],
            ['name'=>'VILLA RICA'                    ,'code'=>'98' ],
            ['name'=>'VALLEDUPAR'                    ,'code'=>'1'  ],
            ['name'=>'AGUACHICA'                     ,'code'=>'75' ],
            ['name'=>'AGUSTIN CODAZZI'               ,'code'=>'150'],
            ['name'=>'ASTREA'                        ,'code'=>'170'],
            ['name'=>'BECERRIL'                      ,'code'=>'180'],
            ['name'=>'BOSCONIA'                      ,'code'=>'200'],
            ['name'=>'CURUMANI'                      ,'code'=>'225'],
            ['name'=>'CHIMICHAGUA'                   ,'code'=>'300'],
            ['name'=>'CHIRIGUANA'                    ,'code'=>'375'],
            ['name'=>'EL COPEY'                      ,'code'=>'410'],
            ['name'=>'EL PASO'                       ,'code'=>'415'],
            ['name'=>'GAMARRA'                       ,'code'=>'450'],
            ['name'=>'GONZALEZ'                      ,'code'=>'525'],
            ['name'=>'LA GLORIA'                     ,'code'=>'600'],
            ['name'=>'LA JAGUA DE IBIRICO'           ,'code'=>'608'],
            ['name'=>'MANAURE BALCON DEL CESAR (MANA','code'=>'625'],
            ['name'=>'PAILITAS'                      ,'code'=>'650'],
            ['name'=>'PELAYA'                        ,'code'=>'700'],
            ['name'=>'PUEBLO BELLO'                  ,'code'=>'720'],
            ['name'=>'RIO DE ORO'                    ,'code'=>'750'],
            ['name'=>'SAN ALBERTO'                   ,'code'=>'800'],
            ['name'=>'LA PAZ'                        ,'code'=>'825'],
            ['name'=>'SAN DIEGO'                     ,'code'=>'850'],
            ['name'=>'SAN MARTIN'                    ,'code'=>'875'],
            ['name'=>'TAMALAMEQUE'                   ,'code'=>'900'],
            ['name'=>'MONTERIA'                      ,'code'=>'1'  ],
            ['name'=>'AYAPEL'                        ,'code'=>'4'  ],
            ['name'=>'BUENAVISTA'                    ,'code'=>'7'  ],
            ['name'=>'CANALETE'                      ,'code'=>'9'  ],
            ['name'=>'CERETE'                        ,'code'=>'10' ],
            ['name'=>'CIENAGA DE ORO'                ,'code'=>'13' ],
            ['name'=>'COTORRA (BONGO)'               ,'code'=>'14' ],
            ['name'=>'CHIMA'                         ,'code'=>'16' ],
            ['name'=>'CHINU'                         ,'code'=>'19' ],
            ['name'=>'LA APARTADA (FRONTERA)'        ,'code'=>'20' ],
            ['name'=>'LORICA'                        ,'code'=>'22' ],
            ['name'=>'LOS CORDOBAS'                  ,'code'=>'23' ],
            ['name'=>'MOMIL'                         ,'code'=>'24' ],
            ['name'=>'MONTELIBANO'                   ,'code'=>'25' ],
            ['name'=>'MOÑITOS'                       ,'code'=>'27' ],
            ['name'=>'PLANETA RICA'                  ,'code'=>'28' ],
            ['name'=>'PUEBLO NUEVO'                  ,'code'=>'31' ],
            ['name'=>'PUERTO LIBERTADOR'             ,'code'=>'32' ],
            ['name'=>'PUERTO ESCONDIDO'              ,'code'=>'33' ],
            ['name'=>'PURISIMA'                      ,'code'=>'34' ],
            ['name'=>'SAHAGUN'                       ,'code'=>'37' ],
            ['name'=>'SAN ANDRES DE SOTAVENTO'       ,'code'=>'40' ],
            ['name'=>'SAN ANTERO'                    ,'code'=>'43' ],
            ['name'=>'SAN BERNARDO DEL VIENTO'       ,'code'=>'46' ],
            ['name'=>'SAN CARLOS'                    ,'code'=>'49' ],
            ['name'=>'SAN JOSE DE URE'               ,'code'=>'52' ],
            ['name'=>'SAN PELAYO'                    ,'code'=>'55' ],
            ['name'=>'TIERRALTA'                     ,'code'=>'58' ],
            ['name'=>'TUCHIN'                        ,'code'=>'60' ],
            ['name'=>'VALENCIA'                      ,'code'=>'61' ],
            ['name'=>'AGUA DE DIOS'                  ,'code'=>'4'  ],
            ['name'=>'ALBAN'                         ,'code'=>'7'  ],
            ['name'=>'ANAPOIMA'                      ,'code'=>'10' ],
            ['name'=>'ANOLAIMA'                      ,'code'=>'13' ],
            ['name'=>'ARBELAEZ'                      ,'code'=>'16' ],
            ['name'=>'BELTRAN'                       ,'code'=>'19' ],
            ['name'=>'BITUIMA'                       ,'code'=>'22' ],
            ['name'=>'BOJACA'                        ,'code'=>'25' ],
            ['name'=>'CABRERA'                       ,'code'=>'29' ],
            ['name'=>'CACHIPAY'                      ,'code'=>'30' ],
            ['name'=>'CAJICA'                        ,'code'=>'31' ],
            ['name'=>'CAPARRAPI'                     ,'code'=>'34' ],
            ['name'=>'CAQUEZA'                       ,'code'=>'37' ],
            ['name'=>'CARMEN DE CARUPA'              ,'code'=>'40' ],
            ['name'=>'COGUA'                         ,'code'=>'43' ],
            ['name'=>'COTA'                          ,'code'=>'46' ],
            ['name'=>'CUCUNUBA'                      ,'code'=>'49' ],
            ['name'=>'CHAGUANI'                      ,'code'=>'52' ],
            ['name'=>'CHIA'                          ,'code'=>'55' ],
            ['name'=>'CHIPAQUE'                      ,'code'=>'58' ],
            ['name'=>'CHOACHI'                       ,'code'=>'61' ],
            ['name'=>'CHOCONTA'                      ,'code'=>'64' ],
            ['name'=>'EL COLEGIO'                    ,'code'=>'67' ],
            ['name'=>'EL PEÑON'                      ,'code'=>'70' ],
            ['name'=>'EL ROSAL'                      ,'code'=>'72' ],
            ['name'=>'FACATATIVA'                    ,'code'=>'76' ],
            ['name'=>'FOMEQUE'                       ,'code'=>'79' ],
            ['name'=>'FOSCA'                         ,'code'=>'85' ],
            ['name'=>'FUNZA'                         ,'code'=>'88' ],
            ['name'=>'FUQUENE'                       ,'code'=>'91' ],
            ['name'=>'FUSAGASUGA'                    ,'code'=>'94' ],
            ['name'=>'GACHALA'                       ,'code'=>'97' ],
            ['name'=>'GACHANCIPA'                    ,'code'=>'100'],
            ['name'=>'GACHETA'                       ,'code'=>'103'],
            ['name'=>'GAMA'                          ,'code'=>'106'],
            ['name'=>'GIRARDOT'                      ,'code'=>'109'],
            ['name'=>'GUACHETA'                      ,'code'=>'112'],
            ['name'=>'GUADUAS'                       ,'code'=>'115'],
            ['name'=>'GUASCA'                        ,'code'=>'118'],
            ['name'=>'GUATAQUI'                      ,'code'=>'121'],
            ['name'=>'GUATAVITA'                     ,'code'=>'124'],
            ['name'=>'GUAYABAL DE SIQUIMA'           ,'code'=>'127'],
            ['name'=>'GUAYABETAL'                    ,'code'=>'128'],
            ['name'=>'GUTIERREZ'                     ,'code'=>'130'],
            ['name'=>'GRANADA'                       ,'code'=>'132'],
            ['name'=>'JERUSALEN'                     ,'code'=>'133'],
            ['name'=>'JUNIN'                         ,'code'=>'136'],
            ['name'=>'LA CALERA'                     ,'code'=>'139'],
            ['name'=>'LA MESA'                       ,'code'=>'142'],
            ['name'=>'LA PALMA'                      ,'code'=>'145'],
            ['name'=>'LA PEÑA'                       ,'code'=>'148'],
            ['name'=>'LA VEGA'                       ,'code'=>'151'],
            ['name'=>'LENGUAZAQUE'                   ,'code'=>'154'],
            ['name'=>'MACHETA'                       ,'code'=>'157'],
            ['name'=>'MADRID'                        ,'code'=>'160'],
            ['name'=>'MANTA'                         ,'code'=>'163'],
            ['name'=>'MEDINA'                        ,'code'=>'166'],
            ['name'=>'MOSQUERA'                      ,'code'=>'169'],
            ['name'=>'NARIÑO'                        ,'code'=>'172'],
            ['name'=>'NEMOCON'                       ,'code'=>'175'],
            ['name'=>'NILO'                          ,'code'=>'178'],
            ['name'=>'NIMAIMA'                       ,'code'=>'181'],
            ['name'=>'NOCAIMA'                       ,'code'=>'184'],
            ['name'=>'PACHO'                         ,'code'=>'190'],
            ['name'=>'PAIME'                         ,'code'=>'193'],
            ['name'=>'PANDI'                         ,'code'=>'196'],
            ['name'=>'PARATEBUENO (LA NAGUAYA)'      ,'code'=>'198'],
            ['name'=>'PASCA'                         ,'code'=>'199'],
            ['name'=>'PUERTO SALGAR'                 ,'code'=>'202'],
            ['name'=>'PULI'                          ,'code'=>'205'],
            ['name'=>'QUEBRADANEGRA'                 ,'code'=>'208'],
            ['name'=>'QUETAME'                       ,'code'=>'211'],
            ['name'=>'QUIPILE'                       ,'code'=>'214'],
            ['name'=>'APULO'                         ,'code'=>'217'],
            ['name'=>'RICAURTE'                      ,'code'=>'218'],
            ['name'=>'SAN ANTONIO DEL TEQUENDAMA'    ,'code'=>'220'],
            ['name'=>'SAN BERNARDO'                  ,'code'=>'223'],
            ['name'=>'SAN CAYETANO'                  ,'code'=>'226'],
            ['name'=>'SAN FRANCISCO'                 ,'code'=>'229'],
            ['name'=>'SAN JUAN DE RIOSECO'           ,'code'=>'232'],
            ['name'=>'SASAIMA'                       ,'code'=>'235'],
            ['name'=>'SESQUILE'                      ,'code'=>'238'],
            ['name'=>'SIBATE'                        ,'code'=>'239'],
            ['name'=>'SILVANIA'                      ,'code'=>'241'],
            ['name'=>'SIMIJACA'                      ,'code'=>'244'],
            ['name'=>'SOACHA'                        ,'code'=>'247'],
            ['name'=>'SOPO'                          ,'code'=>'250'],
            ['name'=>'SUBACHOQUE'                    ,'code'=>'256'],
            ['name'=>'SUESCA'                        ,'code'=>'259'],
            ['name'=>'SUPATA'                        ,'code'=>'262'],
            ['name'=>'SUSA'                          ,'code'=>'265'],
            ['name'=>'SUTATAUSA'                     ,'code'=>'268'],
            ['name'=>'TABIO'                         ,'code'=>'271'],
            ['name'=>'TAUSA'                         ,'code'=>'274'],
            ['name'=>'TENA'                          ,'code'=>'277'],
            ['name'=>'TENJO'                         ,'code'=>'280'],
            ['name'=>'TIBACUY'                       ,'code'=>'283'],
            ['name'=>'TIBIRITA'                      ,'code'=>'286'],
            ['name'=>'TOCAIMA'                       ,'code'=>'289'],
            ['name'=>'TOCANCIPA'                     ,'code'=>'292'],
            ['name'=>'TOPAIPI'                       ,'code'=>'295'],
            ['name'=>'UBALA'                         ,'code'=>'298'],
            ['name'=>'UBAQUE'                        ,'code'=>'301'],
            ['name'=>'UBATE'                         ,'code'=>'304'],
            ['name'=>'UNE'                           ,'code'=>'307'],
            ['name'=>'UTICA'                         ,'code'=>'316'],
            ['name'=>'VENECIA'                       ,'code'=>'318'],
            ['name'=>'VERGARA'                       ,'code'=>'319'],
            ['name'=>'VIANI'                         ,'code'=>'322'],
            ['name'=>'VILLAGOMEZ'                    ,'code'=>'323'],
            ['name'=>'VILLAPINZON'                   ,'code'=>'325'],
            ['name'=>'VILLETA'                       ,'code'=>'328'],
            ['name'=>'VIOTA'                         ,'code'=>'331'],
            ['name'=>'YACOPI'                        ,'code'=>'334'],
            ['name'=>'ZIPACON'                       ,'code'=>'337'],
            ['name'=>'ZIPAQUIRA'                     ,'code'=>'340'],
            ['name'=>'QUIBDO'                        ,'code'=>'1'  ],
            ['name'=>'ATRATO (YUTO)'                 ,'code'=>'2'  ],
            ['name'=>'ACANDI'                        ,'code'=>'4'  ],
            ['name'=>'ALTO BAUDO (PIE DE PATO)'      ,'code'=>'6'  ],
            ['name'=>'BAGADO'                        ,'code'=>'7'  ],
            ['name'=>'BAHIA SOLANO (MUTIS)'          ,'code'=>'8'  ],
            ['name'=>'BAJO BAUDO (PIZARRO)'          ,'code'=>'10' ],
            ['name'=>'BOJAYA (BELLAVISTA)'           ,'code'=>'11' ],
            ['name'=>'MEDIO ATRATO (BETE)'           ,'code'=>'12' ],
            ['name'=>'CONDOTO'                       ,'code'=>'13' ],
            ['name'=>'CERTEGUI'                      ,'code'=>'14' ],
            ['name'=>'CARMEN DEL DARIEN'             ,'code'=>'15' ],
            ['name'=>'EL CARMEN'                     ,'code'=>'16' ],
            ['name'=>'EL CANTON DEL SAN PABLO (MAN.' ,'code'=>'17' ],
            ['name'=>'ISTMINA'                       ,'code'=>'19' ],
            ['name'=>'JURADO'                        ,'code'=>'22' ],
            ['name'=>'LLORO'                         ,'code'=>'25' ],
            ['name'=>'MEDIO BAUDO (PUERTO MELUK)'    ,'code'=>'26' ],
            ['name'=>'MEDIO SAN JUAN'                ,'code'=>'27' ],
            ['name'=>'NOVITA'                        ,'code'=>'28' ],
            ['name'=>'NUQUI'                         ,'code'=>'31' ],
            ['name'=>'RIO IRO'                       ,'code'=>'32' ],
            ['name'=>'RIOSUCIO'                      ,'code'=>'34' ],
            ['name'=>'RIO QUITO (PAIMADO)'           ,'code'=>'35' ],
            ['name'=>'SAN JOSE DEL PALMAR'           ,'code'=>'37' ],
            ['name'=>'EL LITORAL DEL SAN JUAN'       ,'code'=>'38' ],
            ['name'=>'SIPI'                          ,'code'=>'40' ],
            ['name'=>'TADO'                          ,'code'=>'43' ],
            ['name'=>'UNGUIA'                        ,'code'=>'48' ],
            ['name'=>'UNION PANAMERICANA (LAS ANIMAS','code'=>'60' ],
            ['name'=>'NEIVA'                         ,'code'=>'1'  ],
            ['name'=>'ACEVEDO'                       ,'code'=>'4'  ],
            ['name'=>'AGRADO'                        ,'code'=>'7'  ],
            ['name'=>'AIPE'                          ,'code'=>'10' ],
            ['name'=>'ALGECIRAS'                     ,'code'=>'13' ],
            ['name'=>'ALTAMIRA'                      ,'code'=>'16' ],
            ['name'=>'BARAYA'                        ,'code'=>'19' ],
            ['name'=>'CAMPOALEGRE'                   ,'code'=>'22' ],
            ['name'=>'TESALIA (CARNICERIAS)'         ,'code'=>'25' ],
            ['name'=>'COLOMBIA'                      ,'code'=>'28' ],
            ['name'=>'ELIAS'                         ,'code'=>'31' ],
            ['name'=>'GARZON'                        ,'code'=>'34' ],
            ['name'=>'GIGANTE'                       ,'code'=>'37' ],
            ['name'=>'GUADALUPE'                     ,'code'=>'40' ],
            ['name'=>'HOBO'                          ,'code'=>'43' ],
            ['name'=>'ISNOS'                         ,'code'=>'44' ],
            ['name'=>'IQUIRA'                        ,'code'=>'46' ],
            ['name'=>'LA ARGENTINA (PLATA VIEJA)'    ,'code'=>'47' ],
            ['name'=>'LA PLATA'                      ,'code'=>'49' ],
            ['name'=>'NATAGA'                        ,'code'=>'50' ],
            ['name'=>'OPORAPA'                       ,'code'=>'51' ],
            ['name'=>'PAICOL'                        ,'code'=>'52' ],
            ['name'=>'PALERMO'                       ,'code'=>'55' ],
            ['name'=>'PALESTINA'                     ,'code'=>'56' ],
            ['name'=>'PITAL'                         ,'code'=>'58' ],
            ['name'=>'PITALITO'                      ,'code'=>'61' ],
            ['name'=>'RIVERA'                        ,'code'=>'64' ],
            ['name'=>'SALADOBLANCO'                  ,'code'=>'67' ],
            ['name'=>'SAN AGUSTIN'                   ,'code'=>'70' ],
            ['name'=>'SANTA MARIA'                   ,'code'=>'74' ],
            ['name'=>'SUAZA'                         ,'code'=>'76' ],
            ['name'=>'TARQUI'                        ,'code'=>'79' ],
            ['name'=>'TELLO'                         ,'code'=>'82' ],
            ['name'=>'TERUEL'                        ,'code'=>'85' ],
            ['name'=>'TIMANA'                        ,'code'=>'88' ],
            ['name'=>'VILLAVIEJA'                    ,'code'=>'91' ],
            ['name'=>'YAGUARA'                       ,'code'=>'94' ],
            ['name'=>'SANTA MARTA'                   ,'code'=>'1'  ],
            ['name'=>'ALGARROBO'                     ,'code'=>'8'  ],
            ['name'=>'ARACATACA'                     ,'code'=>'10' ],
            ['name'=>'ARIGUANI (EL DIFICIL)'         ,'code'=>'12' ],
            ['name'=>'CERRO DE SAN ANTONIO'          ,'code'=>'13' ],
            ['name'=>'CHIVOLO'                       ,'code'=>'15' ],
            ['name'=>'CIENAGA'                       ,'code'=>'16' ],
            ['name'=>'CONCORDIA'                     ,'code'=>'20' ],
            ['name'=>'EL BANCO'                      ,'code'=>'25' ],
            ['name'=>'EL PIÑON'                      ,'code'=>'28' ],
            ['name'=>'EL RETEN'                      ,'code'=>'30' ],
            ['name'=>'FUNDACION'                     ,'code'=>'31' ],
            ['name'=>'GUAMAL'                        ,'code'=>'40' ],
            ['name'=>'NUEVA GRANADA'                 ,'code'=>'42' ],
            ['name'=>'PEDRAZA'                       ,'code'=>'46' ],
            ['name'=>'PIJIÑO DEL CARMEN'             ,'code'=>'48' ],
            ['name'=>'PIVIJAY'                       ,'code'=>'49' ],
            ['name'=>'PLATO'                         ,'code'=>'52' ],
            ['name'=>'PUEBLOVIEJO'                   ,'code'=>'55' ],
            ['name'=>'REMOLINO'                      ,'code'=>'58' ],
            ['name'=>'SABANAS DE SAN ANGEL'          ,'code'=>'60' ],
            ['name'=>'SALAMINA'                      ,'code'=>'67' ],
            ['name'=>'SAN SEBASTIAN DE BUENAVISTA'   ,'code'=>'70' ],
            ['name'=>'SAN ZENON'                     ,'code'=>'73' ],
            ['name'=>'SANTA ANA'                     ,'code'=>'76' ],
            ['name'=>'SANTA BARBARA DE PINTO'        ,'code'=>'78' ],
            ['name'=>'SITIONUEVO'                    ,'code'=>'79' ],
            ['name'=>'TENERIFE'                      ,'code'=>'85' ],
            ['name'=>'ZAPAYAN'                       ,'code'=>'90' ],
            ['name'=>'ZONA BANANERA (SEVILLA)'       ,'code'=>'95' ],
            ['name'=>'PASTO'                         ,'code'=>'1'  ],
            ['name'=>'ALBAN (SAN JOSE)'              ,'code'=>'4'  ],
            ['name'=>'ALDANA'                        ,'code'=>'7'  ],
            ['name'=>'ANCUYA'                        ,'code'=>'10' ],
            ['name'=>'ARBOLEDA (BERRUECOS)'          ,'code'=>'13' ],
            ['name'=>'BARBACOAS'                     ,'code'=>'16' ],
            ['name'=>'BELEN'                         ,'code'=>'17' ],
            ['name'=>'BUESACO'                       ,'code'=>'19' ],
            ['name'=>'COLON (GENOVA)'                ,'code'=>'22' ],
            ['name'=>'CONSACA'                       ,'code'=>'25' ],
            ['name'=>'CONTADERO'                     ,'code'=>'28' ],
            ['name'=>'CORDOBA'                       ,'code'=>'31' ],
            ['name'=>'CUASPUD (CARLOSAMA)'           ,'code'=>'34' ],
            ['name'=>'CUMBAL'                        ,'code'=>'37' ],
            ['name'=>'CHACHAGUI'                     ,'code'=>'38' ],
            ['name'=>'CUMBITARA'                     ,'code'=>'39' ],
            ['name'=>'EL ROSARIO'                    ,'code'=>'40' ],
            ['name'=>'EL CHARCO'                     ,'code'=>'41' ],
            ['name'=>'EL TABLON'                     ,'code'=>'43' ],
            ['name'=>'EL PEÑOL'                      ,'code'=>'44' ],
            ['name'=>'EL TAMBO'                      ,'code'=>'46' ],
            ['name'=>'FRANCISCO PIZARRO (SALAHONDA)' ,'code'=>'47' ],
            ['name'=>'FUNES'                         ,'code'=>'49' ],
            ['name'=>'GUACHUCAL'                     ,'code'=>'52' ],
            ['name'=>'GUAITARILLA'                   ,'code'=>'55' ],
            ['name'=>'GUALMATAN'                     ,'code'=>'58' ],
            ['name'=>'ILES'                          ,'code'=>'61' ],
            ['name'=>'IMUES'                         ,'code'=>'64' ],
            ['name'=>'IPIALES'                       ,'code'=>'67' ],
            ['name'=>'LA CRUZ'                       ,'code'=>'73' ],
            ['name'=>'LA FLORIDA'                    ,'code'=>'76' ],
            ['name'=>'LA LLANADA'                    ,'code'=>'77' ],
            ['name'=>'LA TOLA'                       ,'code'=>'78' ],
            ['name'=>'LA UNION'                      ,'code'=>'79' ],
            ['name'=>'LEIVA'                         ,'code'=>'80' ],
            ['name'=>'LINARES'                       ,'code'=>'82' ],
            ['name'=>'LOS ANDES (SOTOMAYOR)'         ,'code'=>'85' ],
            ['name'=>'MAGUI (PAYAN)'                 ,'code'=>'88' ],
            ['name'=>'MALLAMA (PIEDRANCHA)'          ,'code'=>'91' ],
            ['name'=>'MOSQUERA'                      ,'code'=>'94' ],
            ['name'=>'OLAYA HERRERA'                 ,'code'=>'95' ],
            ['name'=>'NARIÑO'                        ,'code'=>'96' ],
            ['name'=>'OSPINA'                        ,'code'=>'97' ],
            ['name'=>'POLICARPA'                     ,'code'=>'98' ],
            ['name'=>'POTOSI'                        ,'code'=>'100'],
            ['name'=>'PROVIDENCIA'                   ,'code'=>'101'],
            ['name'=>'PUERRES'                       ,'code'=>'103'],
            ['name'=>'PUPIALES'                      ,'code'=>'106'],
            ['name'=>'RICAURTE'                      ,'code'=>'109'],
            ['name'=>'ROBERTO PAYAN (SAN JOSE)'      ,'code'=>'112'],
            ['name'=>'SAMANIEGO'                     ,'code'=>'115'],
            ['name'=>'SANDONA'                       ,'code'=>'118'],
            ['name'=>'SAN BERNARDO'                  ,'code'=>'120'],
            ['name'=>'SAN LORENZO'                   ,'code'=>'121'],
            ['name'=>'SAN PEDRO DE CARTAGO'          ,'code'=>'123'],
            ['name'=>'SAN PABLO'                     ,'code'=>'124'],
            ['name'=>'SANTA BARBARA (ISCUANDE)'      ,'code'=>'125'],
            ['name'=>'SANTACRUZ (GUACHAVES)'         ,'code'=>'127'],
            ['name'=>'SAPUYES'                       ,'code'=>'130'],
            ['name'=>'TAMINANGO'                     ,'code'=>'133'],
            ['name'=>'TANGUA'                        ,'code'=>'136'],
            ['name'=>'TUMACO'                        ,'code'=>'139'],
            ['name'=>'TUQUERRES'                     ,'code'=>'142'],
            ['name'=>'YACUANQUER'                    ,'code'=>'145'],
            ['name'=>'PEREIRA'                       ,'code'=>'1'  ],
            ['name'=>'APIA'                          ,'code'=>'8'  ],
            ['name'=>'BALBOA'                        ,'code'=>'13' ],
            ['name'=>'BELEN DE UMBRIA'               ,'code'=>'21' ],
            ['name'=>'DOSQUEBRADAS'                  ,'code'=>'25' ],
            ['name'=>'GUATICA'                       ,'code'=>'29' ],
            ['name'=>'LA CELIA'                      ,'code'=>'38' ],
            ['name'=>'LA VIRGINIA'                   ,'code'=>'46' ],
            ['name'=>'MARSELLA'                      ,'code'=>'54' ],
            ['name'=>'MISTRATO'                      ,'code'=>'62' ],
            ['name'=>'PUEBLO RICO'                   ,'code'=>'70' ],
            ['name'=>'QUINCHIA'                      ,'code'=>'78' ],
            ['name'=>'SANTA ROSA DE CABAL'           ,'code'=>'86' ],
            ['name'=>'SANTUARIO'                     ,'code'=>'94' ],
            ['name'=>'CUCUTA'                        ,'code'=>'1'  ],
            ['name'=>'ABREGO'                        ,'code'=>'4'  ],
            ['name'=>'ARBOLEDAS'                     ,'code'=>'7'  ],
            ['name'=>'BOCHALEMA'                     ,'code'=>'10' ],
            ['name'=>'BUCARASICA'                    ,'code'=>'13' ],
            ['name'=>'CACOTA'                        ,'code'=>'16' ],
            ['name'=>'CACHIRA'                       ,'code'=>'19' ],
            ['name'=>'CONVENCION'                    ,'code'=>'22' ],
            ['name'=>'CUCUTILLA'                     ,'code'=>'25' ],
            ['name'=>'CHINACOTA'                     ,'code'=>'28' ],
            ['name'=>'CHITAGA'                       ,'code'=>'31' ],
            ['name'=>'DURANIA'                       ,'code'=>'34' ],
            ['name'=>'EL TARRA'                      ,'code'=>'36' ],
            ['name'=>'EL CARMEN'                     ,'code'=>'37' ],
            ['name'=>'EL ZULIA'                      ,'code'=>'38' ],
            ['name'=>'GRAMALOTE'                     ,'code'=>'40' ],
            ['name'=>'HACARI'                        ,'code'=>'43' ],
            ['name'=>'HERRAN'                        ,'code'=>'46' ],
            ['name'=>'LABATECA'                      ,'code'=>'49' ],
            ['name'=>'LA ESPERANZA'                  ,'code'=>'51' ],
            ['name'=>'LA PLAYA'                      ,'code'=>'52' ],
            ['name'=>'LOS PATIOS'                    ,'code'=>'54' ],
            ['name'=>'LOURDES'                       ,'code'=>'55' ],
            ['name'=>'MUTISCUA'                      ,'code'=>'58' ],
            ['name'=>'OCAÑA'                         ,'code'=>'61' ],
            ['name'=>'PAMPLONA'                      ,'code'=>'64' ],
            ['name'=>'PAMPLONITA'                    ,'code'=>'67' ],
            ['name'=>'PUERTO SANTANDER'              ,'code'=>'69' ],
            ['name'=>'RAGONVALIA'                    ,'code'=>'70' ],
            ['name'=>'SALAZAR'                       ,'code'=>'73' ],
            ['name'=>'SAN CALIXTO'                   ,'code'=>'76' ],
            ['name'=>'SAN CAYETANO'                  ,'code'=>'79' ],
            ['name'=>'SANTIAGO'                      ,'code'=>'82' ],
            ['name'=>'SARDINATA'                     ,'code'=>'85' ],
            ['name'=>'SILOS'                         ,'code'=>'88' ],
            ['name'=>'TEORAMA'                       ,'code'=>'91' ],
            ['name'=>'TIBU'                          ,'code'=>'93' ],
            ['name'=>'TOLEDO'                        ,'code'=>'94' ],
            ['name'=>'VILLA CARO'                    ,'code'=>'97' ],
            ['name'=>'VILLA DEL ROSARIO'             ,'code'=>'100'],
            ['name'=>'ARMENIA'                       ,'code'=>'1'  ],
            ['name'=>'BUENAVISTA'                    ,'code'=>'5'  ],
            ['name'=>'CALARCA'                       ,'code'=>'10' ],
            ['name'=>'CIRCASIA'                      ,'code'=>'20' ],
            ['name'=>'CORDOBA'                       ,'code'=>'25' ],
            ['name'=>'FILANDIA'                      ,'code'=>'30' ],
            ['name'=>'GENOVA'                        ,'code'=>'40' ],
            ['name'=>'LA TEBAIDA'                    ,'code'=>'50' ],
            ['name'=>'MONTENEGRO'                    ,'code'=>'60' ],
            ['name'=>'PIJAO'                         ,'code'=>'70' ],
            ['name'=>'QUIMBAYA'                      ,'code'=>'80' ],
            ['name'=>'SALENTO'                       ,'code'=>'90' ],
            ['name'=>'BUCARAMANGA'                   ,'code'=>'1'  ],
            ['name'=>'AGUADA'                        ,'code'=>'4'  ],
            ['name'=>'ALBANIA'                       ,'code'=>'7'  ],
            ['name'=>'ARATOCA'                       ,'code'=>'10' ],
            ['name'=>'BARBOSA'                       ,'code'=>'13' ],
            ['name'=>'BARICHARA'                     ,'code'=>'16' ],
            ['name'=>'BARRANCABERMEJA'               ,'code'=>'19' ],
            ['name'=>'BETULIA'                       ,'code'=>'22' ],
            ['name'=>'BOLIVAR'                       ,'code'=>'25' ],
            ['name'=>'CABRERA'                       ,'code'=>'28' ],
            ['name'=>'CALIFORNIA'                    ,'code'=>'31' ],
            ['name'=>'CAPITANEJO'                    ,'code'=>'34' ],
            ['name'=>'CARCASI'                       ,'code'=>'37' ],
            ['name'=>'CEPITA'                        ,'code'=>'40' ],
            ['name'=>'CERRITO'                       ,'code'=>'43' ],
            ['name'=>'CIMITARRA'                     ,'code'=>'45' ],
            ['name'=>'CONCEPCION'                    ,'code'=>'46' ],
            ['name'=>'CONFINES'                      ,'code'=>'49' ],
            ['name'=>'CONTRATACION'                  ,'code'=>'52' ],
            ['name'=>'COROMORO'                      ,'code'=>'55' ],
            ['name'=>'CURITI'                        ,'code'=>'58' ],
            ['name'=>'CHARALA'                       ,'code'=>'61' ],
            ['name'=>'CHARTA'                        ,'code'=>'64' ],
            ['name'=>'CHIMA'                         ,'code'=>'67' ],
            ['name'=>'CHIPATA'                       ,'code'=>'70' ],
            ['name'=>'EL CARMEN'                     ,'code'=>'71' ],
            ['name'=>'EL GUACAMAYO'                  ,'code'=>'73' ],
            ['name'=>'EL PLAYON'                     ,'code'=>'74' ],
            ['name'=>'EL PEÑON'                      ,'code'=>'75' ],
            ['name'=>'ENCINO'                        ,'code'=>'76' ],
            ['name'=>'ENCISO'                        ,'code'=>'79' ],
            ['name'=>'FLORIAN'                       ,'code'=>'80' ],
            ['name'=>'FLORIDABLANCA'                 ,'code'=>'82' ],
            ['name'=>'GALAN'                         ,'code'=>'85' ],
            ['name'=>'GAMBITA'                       ,'code'=>'88' ],
            ['name'=>'GIRON'                         ,'code'=>'91' ],
            ['name'=>'GUACA'                         ,'code'=>'94' ],
            ['name'=>'GUADALUPE'                     ,'code'=>'97' ],
            ['name'=>'GUAPOTA'                       ,'code'=>'100'],
            ['name'=>'GUAVATA'                       ,'code'=>'103'],
            ['name'=>'GUEPSA'                        ,'code'=>'106'],
            ['name'=>'HATO'                          ,'code'=>'109'],
            ['name'=>'JESUS MARIA'                   ,'code'=>'112'],
            ['name'=>'JORDAN'                        ,'code'=>'115'],
            ['name'=>'LA PAZ'                        ,'code'=>'118'],
            ['name'=>'LA BELLEZA'                    ,'code'=>'119'],
            ['name'=>'LANDAZURI'                     ,'code'=>'120'],
            ['name'=>'LEBRIJA'                       ,'code'=>'121'],
            ['name'=>'LOS SANTOS'                    ,'code'=>'124'],
            ['name'=>'MACARAVITA'                    ,'code'=>'127'],
            ['name'=>'MALAGA'                        ,'code'=>'130'],
            ['name'=>'MATANZA'                       ,'code'=>'133'],
            ['name'=>'MOGOTES'                       ,'code'=>'136'],
            ['name'=>'MOLAGAVITA'                    ,'code'=>'139'],
            ['name'=>'OCAMONTE'                      ,'code'=>'142'],
            ['name'=>'OIBA'                          ,'code'=>'145'],
            ['name'=>'ONZAGA'                        ,'code'=>'148'],
            ['name'=>'PALMAR'                        ,'code'=>'151'],
            ['name'=>'PALMAS DEL SOCORRO'            ,'code'=>'154'],
            ['name'=>'PARAMO'                        ,'code'=>'157'],
            ['name'=>'PIEDECUESTA'                   ,'code'=>'160'],
            ['name'=>'PINCHOTE'                      ,'code'=>'163'],
            ['name'=>'PUENTE NACIONAL'               ,'code'=>'166'],
            ['name'=>'PUERTO PARRA'                  ,'code'=>'167'],
            ['name'=>'PUERTO WILCHES'                ,'code'=>'169'],
            ['name'=>'RIONEGRO'                      ,'code'=>'172'],
            ['name'=>'SABANA DE TORRES'              ,'code'=>'174'],
            ['name'=>'SAN ANDRES'                    ,'code'=>'175'],
            ['name'=>'SAN BENITO'                    ,'code'=>'178'],
            ['name'=>'SAN GIL'                       ,'code'=>'181'],
            ['name'=>'SAN JOAQUIN'                   ,'code'=>'184'],
            ['name'=>'SAN JOSE DE MIRANDA'           ,'code'=>'187'],
            ['name'=>'SAN MIGUEL'                    ,'code'=>'190'],
            ['name'=>'SAN VICENTE DE CHUCURI'        ,'code'=>'193'],
            ['name'=>'SANTA HELENA DEL OPON'         ,'code'=>'194'],
            ['name'=>'SANTA BARBARA'                 ,'code'=>'195'],
            ['name'=>'SIMACOTA'                      ,'code'=>'196'],
            ['name'=>'SOCORRO'                       ,'code'=>'199'],
            ['name'=>'SUAITA'                        ,'code'=>'202'],
            ['name'=>'SUCRE'                         ,'code'=>'205'],
            ['name'=>'SURATA'                        ,'code'=>'208'],
            ['name'=>'TONA'                          ,'code'=>'211'],
            ['name'=>'VALLE DE SAN JOSE'             ,'code'=>'217'],
            ['name'=>'VETAS'                         ,'code'=>'219'],
            ['name'=>'VELEZ'                         ,'code'=>'220'],
            ['name'=>'VILLANUEVA'                    ,'code'=>'221'],
            ['name'=>'ZAPATOCA'                      ,'code'=>'223'],
            ['name'=>'SINCELEJO'                     ,'code'=>'1'  ],
            ['name'=>'BUENAVISTA'                    ,'code'=>'10' ],
            ['name'=>'CAIMITO'                       ,'code'=>'20' ],
            ['name'=>'COLOSO (RICAURTE)'             ,'code'=>'30' ],
            ['name'=>'COROZAL'                       ,'code'=>'40' ],
            ['name'=>'COVEÑAS'                       ,'code'=>'41' ],
            ['name'=>'EL ROBLE'                      ,'code'=>'42' ],
            ['name'=>'CHALAN'                        ,'code'=>'45' ],
            ['name'=>'GALERAS (NUEVA GRANADA)'       ,'code'=>'48' ],
            ['name'=>'GUARANDA'                      ,'code'=>'49' ],
            ['name'=>'LA UNION'                      ,'code'=>'50' ],
            ['name'=>'LOS PALMITOS'                  ,'code'=>'55' ],
            ['name'=>'MAJAGUAL'                      ,'code'=>'60' ],
            ['name'=>'MORROA'                        ,'code'=>'80' ],
            ['name'=>'OVEJAS'                        ,'code'=>'100'],
            ['name'=>'PALMITO'                       ,'code'=>'120'],
            ['name'=>'SAMPUES'                       ,'code'=>'160'],
            ['name'=>'SAN BENITO ABAD'               ,'code'=>'180'],
            ['name'=>'SAN JUAN DE BETULIA (BETULIA)' ,'code'=>'190'],
            ['name'=>'SAN MARCOS'                    ,'code'=>'200'],
            ['name'=>'SAN ONOFRE'                    ,'code'=>'220'],
            ['name'=>'SAN PEDRO'                     ,'code'=>'240'],
            ['name'=>'SINCE'                         ,'code'=>'260'],
            ['name'=>'SUCRE'                         ,'code'=>'280'],
            ['name'=>'TOLU'                          ,'code'=>'300'],
            ['name'=>'TOLUVIEJO'                     ,'code'=>'320'],
            ['name'=>'IBAGUE'                        ,'code'=>'1'  ],
            ['name'=>'ALPUJARRA'                     ,'code'=>'4'  ],
            ['name'=>'ALVARADO'                      ,'code'=>'7'  ],
            ['name'=>'AMBALEMA'                      ,'code'=>'10' ],
            ['name'=>'ANZOATEGUI'                    ,'code'=>'13' ],
            ['name'=>'ARMERO (GUAYABAL)'             ,'code'=>'16' ],
            ['name'=>'ATACO'                         ,'code'=>'19' ],
            ['name'=>'CAJAMARCA'                     ,'code'=>'22' ],
            ['name'=>'CARMEN DE APICALA'             ,'code'=>'25' ],
            ['name'=>'CASABIANCA'                    ,'code'=>'28' ],
            ['name'=>'COELLO'                        ,'code'=>'31' ],
            ['name'=>'COYAIMA'                       ,'code'=>'34' ],
            ['name'=>'CUNDAY'                        ,'code'=>'37' ],
            ['name'=>'CHAPARRAL'                     ,'code'=>'40' ],
            ['name'=>'DOLORES'                       ,'code'=>'43' ],
            ['name'=>'ESPINAL'                       ,'code'=>'46' ],
            ['name'=>'FALAN'                         ,'code'=>'49' ],
            ['name'=>'FLANDES'                       ,'code'=>'52' ],
            ['name'=>'FRESNO'                        ,'code'=>'55' ],
            ['name'=>'GUAMO'                         ,'code'=>'58' ],
            ['name'=>'HERVEO'                        ,'code'=>'61' ],
            ['name'=>'HONDA'                         ,'code'=>'64' ],
            ['name'=>'ICONONZO'                      ,'code'=>'67' ],
            ['name'=>'LERIDA'                        ,'code'=>'70' ],
            ['name'=>'LIBANO'                        ,'code'=>'73' ],
            ['name'=>'MARIQUITA'                     ,'code'=>'76' ],
            ['name'=>'MELGAR'                        ,'code'=>'79' ],
            ['name'=>'MURILLO'                       ,'code'=>'80' ],
            ['name'=>'NATAGAIMA'                     ,'code'=>'82' ],
            ['name'=>'ORTEGA'                        ,'code'=>'85' ],
            ['name'=>'PALOCABILDO'                   ,'code'=>'87' ],
            ['name'=>'PIEDRAS'                       ,'code'=>'88' ],
            ['name'=>'PLANADAS'                      ,'code'=>'89' ],
            ['name'=>'PRADO'                         ,'code'=>'91' ],
            ['name'=>'PURIFICACION'                  ,'code'=>'94' ],
            ['name'=>'RIOBLANCO'                     ,'code'=>'97' ],
            ['name'=>'RONCESVALLES'                  ,'code'=>'100'],
            ['name'=>'ROVIRA'                        ,'code'=>'103'],
            ['name'=>'SALDAÑA'                       ,'code'=>'105'],
            ['name'=>'SAN ANTONIO'                   ,'code'=>'106'],
            ['name'=>'SAN LUIS'                      ,'code'=>'109'],
            ['name'=>'SANTA ISABEL'                  ,'code'=>'112'],
            ['name'=>'SUAREZ'                        ,'code'=>'115'],
            ['name'=>'VALLE DE SAN JUAN'             ,'code'=>'118'],
            ['name'=>'VENADILLO'                     ,'code'=>'121'],
            ['name'=>'VILLAHERMOSA'                  ,'code'=>'124'],
            ['name'=>'VILLARRICA'                    ,'code'=>'127'],
            ['name'=>'CALI'                          ,'code'=>'1'  ],
            ['name'=>'ALCALA'                        ,'code'=>'4'  ],
            ['name'=>'ANDALUCIA'                     ,'code'=>'7'  ],
            ['name'=>'ANSERMANUEVO'                  ,'code'=>'10' ],
            ['name'=>'ARGELIA'                       ,'code'=>'13' ],
            ['name'=>'BOLIVAR'                       ,'code'=>'16' ],
            ['name'=>'BUENAVENTURA'                  ,'code'=>'19' ],
            ['name'=>'BUGA'                          ,'code'=>'22' ],
            ['name'=>'BUGALAGRANDE'                  ,'code'=>'25' ],
            ['name'=>'CAICEDONIA'                    ,'code'=>'28' ],
            ['name'=>'CANDELARIA'                    ,'code'=>'31' ],
            ['name'=>'CARTAGO'                       ,'code'=>'34' ],
            ['name'=>'DAGUA'                         ,'code'=>'37' ],
            ['name'=>'CALIMA (DARIEN)'               ,'code'=>'40' ],
            ['name'=>'EL AGUILA'                     ,'code'=>'43' ],
            ['name'=>'EL CAIRO'                      ,'code'=>'46' ],
            ['name'=>'EL CERRITO'                    ,'code'=>'49' ],
            ['name'=>'EL DOVIO'                      ,'code'=>'52' ],
            ['name'=>'FLORIDA'                       ,'code'=>'55' ],
            ['name'=>'GINEBRA'                       ,'code'=>'58' ],
            ['name'=>'GUACARI'                       ,'code'=>'61' ],
            ['name'=>'JAMUNDI'                       ,'code'=>'64' ],
            ['name'=>'LA CUMBRE'                     ,'code'=>'67' ],
            ['name'=>'LA UNION'                      ,'code'=>'70' ],
            ['name'=>'LA VICTORIA'                   ,'code'=>'73' ],
            ['name'=>'OBANDO'                        ,'code'=>'76' ],
            ['name'=>'PALMIRA'                       ,'code'=>'79' ],
            ['name'=>'PRADERA'                       ,'code'=>'82' ],
            ['name'=>'RESTREPO'                      ,'code'=>'85' ],
            ['name'=>'RIOFRIO'                       ,'code'=>'88' ],
            ['name'=>'ROLDANILLO'                    ,'code'=>'91' ],
            ['name'=>'SAN PEDRO'                     ,'code'=>'94' ],
            ['name'=>'SEVILLA'                       ,'code'=>'97' ],
            ['name'=>'TORO'                          ,'code'=>'100'],
            ['name'=>'TRUJILLO'                      ,'code'=>'103'],
            ['name'=>'TULUA'                         ,'code'=>'106'],
            ['name'=>'ULLOA'                         ,'code'=>'109'],
            ['name'=>'VERSALLES'                     ,'code'=>'112'],
            ['name'=>'VIJES'                         ,'code'=>'115'],
            ['name'=>'YOTOCO'                        ,'code'=>'118'],
            ['name'=>'YUMBO'                         ,'code'=>'121'],
            ['name'=>'ZARZAL'                        ,'code'=>'124'],
            ['name'=>'ARAUCA'                        ,'code'=>'1'  ],
            ['name'=>'TAME'                          ,'code'=>'5'  ],
            ['name'=>'ARAUQUITA'                     ,'code'=>'10' ],
            ['name'=>'CRAVO NORTE'                   ,'code'=>'15' ],
            ['name'=>'FORTUL'                        ,'code'=>'17' ],
            ['name'=>'PUERTO RONDON'                 ,'code'=>'20' ],
            ['name'=>'SARAVENA'                      ,'code'=>'25' ],
            ['name'=>'FLORENCIA'                     ,'code'=>'1'  ],
            ['name'=>'ALBANIA'                       ,'code'=>'2'  ],
            ['name'=>'CARTAGENA DEL CHAIRA'          ,'code'=>'3'  ],
            ['name'=>'BELEN DE LOS ANDAQUIES'        ,'code'=>'4'  ],
            ['name'=>'EL DONCELLO'                   ,'code'=>'5'  ],
            ['name'=>'EL PAUJIL'                     ,'code'=>'6'  ],
            ['name'=>'LA MONTAÑITA'                  ,'code'=>'7'  ],
            ['name'=>'PUERTO RICO'                   ,'code'=>'9'  ],
            ['name'=>'SAN VICENTE DEL CAGUAN'        ,'code'=>'10' ],
            ['name'=>'CURILLO'                       ,'code'=>'12' ],
            ['name'=>'MILAN'                         ,'code'=>'16' ],
            ['name'=>'MORELIA'                       ,'code'=>'17' ],
            ['name'=>'SAN JOSE DEL FRAGUA'           ,'code'=>'20' ],
            ['name'=>'SOLANO'                        ,'code'=>'22' ],
            ['name'=>'SOLITA'                        ,'code'=>'24' ],
            ['name'=>'VALPARAISO'                    ,'code'=>'40' ],
            ['name'=>'YOPAL'                         ,'code'=>'1'  ],
            ['name'=>'AGUAZUL'                       ,'code'=>'40' ],
            ['name'=>'CHAMEZA'                       ,'code'=>'120'],
            ['name'=>'HATO COROZAL'                  ,'code'=>'320'],
            ['name'=>'LA SALINA'                     ,'code'=>'480'],
            ['name'=>'MANI'                          ,'code'=>'520'],
            ['name'=>'MONTERREY'                     ,'code'=>'540'],
            ['name'=>'NUNCHIA'                       ,'code'=>'560'],
            ['name'=>'OROCUE'                        ,'code'=>'640'],
            ['name'=>'PAZ DE ARIPORO (MORENO)'       ,'code'=>'680'],
            ['name'=>'PORE'                          ,'code'=>'700'],
            ['name'=>'RECETOR'                       ,'code'=>'760'],
            ['name'=>'SABANALARGA'                   ,'code'=>'800'],
            ['name'=>'SACAMA'                        ,'code'=>'815'],
            ['name'=>'SAN LUIS DE PALENQUE'          ,'code'=>'830'],
            ['name'=>'TAMARA'                        ,'code'=>'840'],
            ['name'=>'TAURAMENA'                     ,'code'=>'850'],
            ['name'=>'TRINIDAD'                      ,'code'=>'865'],
            ['name'=>'VILLANUEVA'                    ,'code'=>'880'],
            ['name'=>'RIOHACHA'                      ,'code'=>'1'  ],
            ['name'=>'BARRANCAS'                     ,'code'=>'4'  ],
            ['name'=>'DIBULLA'                       ,'code'=>'5'  ],
            ['name'=>'EL MOLINO'                     ,'code'=>'6'  ],
            ['name'=>'FONSECA'                       ,'code'=>'7'  ],
            ['name'=>'DISTRACCION'                   ,'code'=>'8'  ],
            ['name'=>'HATONUEVO'                     ,'code'=>'9'  ],
            ['name'=>'MAICAO'                        ,'code'=>'10' ],
            ['name'=>'MANAURE'                       ,'code'=>'11' ],
            ['name'=>'LA JAGUA DEL PILAR'            ,'code'=>'12' ],
            ['name'=>'SAN JUAN DEL CESAR'            ,'code'=>'13' ],
            ['name'=>'URIBIA'                        ,'code'=>'16' ],
            ['name'=>'URUMITA'                       ,'code'=>'18' ],
            ['name'=>'VILLANUEVA'                    ,'code'=>'20' ],
            ['name'=>'INIRIDA'                       ,'code'=>'1'  ],
            ['name'=>'BARRANCOMINAS'                 ,'code'=>'70' ],
            ['name'=>'CACAHUAL'                      ,'code'=>'73' ],
            ['name'=>'LA GUADALUPE'                  ,'code'=>'78' ],
            ['name'=>'MORICHAL (MORICHAL NUEVO)'     ,'code'=>'83' ],
            ['name'=>'PANA PANA (CAMPO ALEGRE)'      ,'code'=>'87' ],
            ['name'=>'PUERTO COLOMBIA'               ,'code'=>'90' ],
            ['name'=>'SAN FELIPE'                    ,'code'=>'92' ],
            ['name'=>'VILLAVICENCIO'                 ,'code'=>'1'  ],
            ['name'=>'ACACIAS'                       ,'code'=>'5'  ],
            ['name'=>'BARRANCA DE UPIA'              ,'code'=>'6'  ],
            ['name'=>'CABUYARO'                      ,'code'=>'8'  ],
            ['name'=>'CASTILLA LA NUEVA'             ,'code'=>'10' ],
            ['name'=>'CUBARRAL'                      ,'code'=>'15' ],
            ['name'=>'CUMARAL'                       ,'code'=>'20' ],
            ['name'=>'EL CALVARIO'                   ,'code'=>'25' ],
            ['name'=>'EL CASTILLO'                   ,'code'=>'27' ],
            ['name'=>'EL DORADO'                     ,'code'=>'28' ],
            ['name'=>'FUENTE DE ORO'                 ,'code'=>'30' ],
            ['name'=>'GRANADA'                       ,'code'=>'35' ],
            ['name'=>'LA MACARENA'                   ,'code'=>'41' ],
            ['name'=>'LEJANIAS'                      ,'code'=>'42' ],
            ['name'=>'PUERTO GAITAN'                 ,'code'=>'43' ],
            ['name'=>'MESETAS'                       ,'code'=>'44' ],
            ['name'=>'PUERTO LOPEZ'                  ,'code'=>'45' ],
            ['name'=>'MAPIRIPAN'                     ,'code'=>'46' ],
            ['name'=>'PUERTO CONCORDIA'              ,'code'=>'47' ],
            ['name'=>'PUERTO LLERAS'                 ,'code'=>'48' ],
            ['name'=>'PUERTO RICO'                   ,'code'=>'49' ],
            ['name'=>'RESTREPO'                      ,'code'=>'50' ],
            ['name'=>'SAN CARLOS DE GUAROA'          ,'code'=>'55' ],
            ['name'=>'SAN JUAN DE ARAMA'             ,'code'=>'58' ],
            ['name'=>'SAN JUANITO'                   ,'code'=>'59' ],
            ['name'=>'SAN MARTIN DE LOS LLANOS'      ,'code'=>'60' ],
            ['name'=>'URIBE'                         ,'code'=>'74' ],
            ['name'=>'VISTA HERMOSA'                 ,'code'=>'80' ],
            ['name'=>'SAN JOSE DEL GUAVIARE'         ,'code'=>'1'  ],
            ['name'=>'CALAMAR'                       ,'code'=>'3'  ],
            ['name'=>'EL RETORNO'                    ,'code'=>'7'  ],
            ['name'=>'MIRAFLORES'                    ,'code'=>'12' ],
            ['name'=>'SAN ANDRES'                    ,'code'=>'1'  ],
            ['name'=>'PROVIDENCIA'                   ,'code'=>'4'  ],
            ['name'=>'LETICIA'                       ,'code'=>'1'  ],
            ['name'=>'PUERTO NARIÑO'                 ,'code'=>'7'  ],
            ['name'=>'EL ENCANTO'                    ,'code'=>'10' ],
            ['name'=>'LA CHORRERA'                   ,'code'=>'13' ],
            ['name'=>'LA PEDRERA'                    ,'code'=>'16' ],
            ['name'=>'LA VICTORIA'                   ,'code'=>'17' ],
            ['name'=>'MIRITI PARANA'                 ,'code'=>'19' ],
            ['name'=>'PUERTO SANTANDER'              ,'code'=>'21' ],
            ['name'=>'TARAPACA'                      ,'code'=>'22' ],
            ['name'=>'PUERTO ALEGRIA'                ,'code'=>'30' ],
            ['name'=>'PUERTO ARICA'                  ,'code'=>'40' ],
            ['name'=>'MOCOA'                         ,'code'=>'1'  ],
            ['name'=>'PUERTO ASIS'                   ,'code'=>'2'  ],
            ['name'=>'PUERTO LEGUIZAMO'              ,'code'=>'4'  ],
            ['name'=>'COLON'                         ,'code'=>'7'  ],
            ['name'=>'SAN FRANCISCO'                 ,'code'=>'13' ],
            ['name'=>'SANTIAGO'                      ,'code'=>'16' ],
            ['name'=>'SAN MIGUEL (LA DORADA)'        ,'code'=>'18' ],
            ['name'=>'SIBUNDOY'                      ,'code'=>'19' ],
            ['name'=>'ORITO'                         ,'code'=>'23' ],
            ['name'=>'PUERTO GUZMAN'                 ,'code'=>'25' ],
            ['name'=>'PUERTO CAICEDO'                ,'code'=>'26' ],
            ['name'=>'VALLE DEL GUAMUEZ (LA HORMIGA)','code'=>'28' ],
            ['name'=>'VILLAGARZON'                   ,'code'=>'30' ],
            ['name'=>'MITU'                          ,'code'=>'1'  ],
            ['name'=>'CARURU'                        ,'code'=>'4'  ],
            ['name'=>'MORICHAL (PAPUNAGUA)'          ,'code'=>'10' ],
            ['name'=>'BUENOS AIRES (PACOA)'          ,'code'=>'13' ],
            ['name'=>'TARAIRA'                       ,'code'=>'17' ],
            ['name'=>'YAVARATE'                      ,'code'=>'22' ],
            ['name'=>'PUERTO CARREÑO'                ,'code'=>'1'  ],
            ['name'=>'SANTA ROSALIA'                 ,'code'=>'2'  ],
            ['name'=>'CUMARIBO'                      ,'code'=>'6'  ],
            ['name'=>'LA PRIMAVERA'                  ,'code'=>'8'  ],
            ['name'=>'BOGOTA. D.C.'                  ,'code'=>'1'  ],

        ];
        
        Municipality::insert($municipalities);
        $this->command->info(__("Municipalities added successfully"));

    }
}
